import type { DatabaseKind } from '../db/repositories/databaseProfilesRepo'

export type NoCodeSqlFieldType = 'text' | 'longText' | 'integer' | 'decimal' | 'date' | 'dateTime' | 'boolean' | 'email' | 'phone'

export interface NoCodeSqlField {
  name: string
  type: NoCodeSqlFieldType
  required: boolean
  length?: number
}

const clamp = (value: number | undefined, fallback: number, maximum: number): number =>
  Math.max(1, Math.min(maximum, Number.isFinite(value) ? Math.trunc(value!) : fallback))

export function quoteNoCodeIdentifier(kind: DatabaseKind, value: string): string {
  if (kind === 'mysql') return `\`${value.replace(/`/g, '``')}\``
  if (kind === 'sqlserver') return `[${value.replace(/]/g, ']]')}]`
  return `"${value.replace(/"/g, '""')}"`
}

function fieldType(kind: DatabaseKind, field: NoCodeSqlField): string {
  const length = clamp(field.length, field.type === 'email' ? 254 : field.type === 'phone' ? 20 : 120, kind === 'oracle' ? 4000 : 8000)
  if (kind === 'sqlite') {
    if (field.type === 'integer' || field.type === 'boolean') return 'INTEGER'
    if (field.type === 'decimal') return 'NUMERIC'
    return 'TEXT'
  }
  if (kind === 'mysql') {
    if (field.type === 'longText') return 'LONGTEXT'
    if (field.type === 'integer') return 'INT'
    if (field.type === 'decimal') return 'DECIMAL(18,2)'
    if (field.type === 'date') return 'DATE'
    if (field.type === 'dateTime') return 'DATETIME'
    if (field.type === 'boolean') return 'BOOLEAN'
    return `VARCHAR(${length})`
  }
  if (kind === 'postgresql') {
    if (field.type === 'longText') return 'TEXT'
    if (field.type === 'integer') return 'INTEGER'
    if (field.type === 'decimal') return 'NUMERIC(18,2)'
    if (field.type === 'date') return 'DATE'
    if (field.type === 'dateTime') return 'TIMESTAMP'
    if (field.type === 'boolean') return 'BOOLEAN'
    return `VARCHAR(${length})`
  }
  if (kind === 'firebird') {
    if (field.type === 'longText') return 'BLOB SUB_TYPE TEXT CHARACTER SET UTF8'
    if (field.type === 'integer') return 'INTEGER'
    if (field.type === 'decimal') return 'NUMERIC(18,2)'
    if (field.type === 'date') return 'DATE'
    if (field.type === 'dateTime') return 'TIMESTAMP'
    if (field.type === 'boolean') return 'BOOLEAN'
    return `VARCHAR(${Math.min(length, 8191)}) CHARACTER SET UTF8`
  }
  if (kind === 'sqlserver') {
    if (field.type === 'longText') return 'NVARCHAR(MAX)'
    if (field.type === 'integer') return 'INT'
    if (field.type === 'decimal') return 'DECIMAL(18,2)'
    if (field.type === 'date') return 'DATE'
    if (field.type === 'dateTime') return 'DATETIME2(0)'
    if (field.type === 'boolean') return 'BIT'
    return `NVARCHAR(${length})`
  }
  if (field.type === 'longText') return 'CLOB'
  if (field.type === 'integer') return 'NUMBER(10)'
  if (field.type === 'decimal') return 'NUMBER(18,2)'
  if (field.type === 'date') return 'DATE'
  if (field.type === 'dateTime') return 'TIMESTAMP'
  if (field.type === 'boolean') return 'NUMBER(1)'
  return `VARCHAR2(${length} CHAR)`
}

function identityColumn(kind: DatabaseKind): string {
  const id = quoteNoCodeIdentifier(kind, 'id')
  if (kind === 'sqlite') return `${id} INTEGER PRIMARY KEY AUTOINCREMENT`
  if (kind === 'mysql') return `${id} BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY`
  if (kind === 'postgresql') return `${id} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`
  if (kind === 'firebird') return `${id} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`
  if (kind === 'sqlserver') return `${id} BIGINT IDENTITY(1,1) PRIMARY KEY`
  return `${id} NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY`
}

export function buildCreateTableSql(kind: DatabaseKind, tableName: string, fields: NoCodeSqlField[]): string {
  const columns = [identityColumn(kind), ...fields.map((field) => {
    const name = quoteNoCodeIdentifier(kind, field.name)
    const nullable = field.required ? ' NOT NULL' : ''
    const booleanCheck = field.type === 'boolean' && (kind === 'sqlite' || kind === 'oracle')
      ? ` CHECK (${name} IN (0, 1))`
      : ''
    return `${name} ${fieldType(kind, field)}${nullable}${booleanCheck}`
  })]
  return `CREATE TABLE ${quoteNoCodeIdentifier(kind, tableName)} (\n  ${columns.join(',\n  ')}\n)`
}

export function buildDropTableSql(kind: DatabaseKind, tableName: string): string {
  return `DROP TABLE ${quoteNoCodeIdentifier(kind, tableName)}`
}

export function databaseDisplayName(kind: DatabaseKind): string {
  return ({ sqlite: 'SQLite', firebird: 'Firebird', mysql: 'MySQL', postgresql: 'PostgreSQL', sqlserver: 'SQL Server', oracle: 'Oracle' })[kind]
}
